# Generated by Django 5.2.7 on 2026-01-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_carshop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('cancelled', 'Anulada')], default='draft', max_length=10),
        ),
    ]
