# Generated by Django 5.2.7 on 2026-05-09 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0006_venta_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-created'], 'verbose_name': 'Ventas'},
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='VD_precio_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['user', 'Venta_Fecha'], name='sales_venta_user_id_a7b696_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['Venta_CliId'], name='sales_venta_Venta_C_24d07b_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['status'], name='sales_venta_status_90708c_idx'),
        ),
    ]
